services:
  - type: web
    name: mediatekformation
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader && php bin/console cache:clear --env=prod
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mediatekformation-db
          property: connectionString

databases:
  - name: mediatekformation-db
    databaseName: mediatekformation
    user: symfony
